import React, { useState } from 'react';
import { Container, Row, Col, Form, Button, Collapse } from 'react-bootstrap';
import { QRCodeSVG } from 'qrcode.react';
import { Helmet } from 'react-helmet-async';
import {
    FaBookOpen, FaInfoCircle, FaPhone, FaMapMarkerAlt,
    FaDownload, FaPrint, FaShareAlt, FaCheck, FaFileAlt, FaLightbulb, FaHistory,
    FaArrowRight, FaCheckCircle
} from 'react-icons/fa';
import { HiOutlineDownload } from 'react-icons/hi';
import '../../css/WiFiQRCodeLandingPage.scss';
import LandingPageFooter from '../LandingPageFooter';

const FAQItem = ({ q, a }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (
        <div className="faq-item-custom mb-3">
            <button
                className={`faq-question-btn ${isOpen ? 'active' : ''}`}
                onClick={() => setIsOpen(!isOpen)}
                aria-expanded={isOpen}
            >
                <span>{q}</span>
                <span className="icon">{isOpen ? '−' : '+'}</span>
            </button>
            <Collapse in={isOpen}>
                <div className="faq-answer-content">
                    <p>{a}</p>
                </div>
            </Collapse>

        </div>
    );
};

const BrochuresQRCodeLandingPage = () => {
    const [brochureTitle, setBrochureTitle] = useState('');
    const [businessName, setBusinessName] = useState('');
    const [ctaText, setCtaText] = useState('');
    const [brochureUrl, setBrochureUrl] = useState('');

    const isAllFieldsFilled = brochureTitle.trim() !== '' && businessName.trim() !== '' && ctaText.trim() !== '' && brochureUrl.trim() !== '';

    const downloadQRCode = () => {
        const svg = document.getElementById('brochure-qr-code');
        if (!svg) return;
        const svgData = new XMLSerializer().serializeToString(svg);
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        const img = new Image();
        img.onload = () => {
            canvas.width = img.width;
            canvas.height = img.height;
            ctx.drawImage(img, 0, 0);
            const pngFile = canvas.toDataURL('image/png');
            const downloadLink = document.createElement('a');
            downloadLink.download = `${brochureTitle || 'brochure'}-qr-code.png`;
            downloadLink.href = pngFile;
            downloadLink.click();
        };
        img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
    };

    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": "How does a QR code benefit a brochure?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "It connects your physical brochure to digital content like videos, expanded pricing, or appointment booking, keeping the brochure design clean and focused."
                }
            },
            {
                "@type": "Question",
                "name": "Can I link to a PDF catalog?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes! Just paste the direct URL of your hosted PDF catalog into the destination link, and customers can view it instantly."
                }
            },
            {
                "@type": "Question",
                "name": "Is there a limit on how many people can scan?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "No. The static QR codes generated by TheQrify have no scan limits and never expire."
                }
            }
        ]
    };

    return (
        <div className="wifi-landing-container no-select">
            <Helmet>
                <title>QR Code for Brochures & Pamphlets | Premium Print QR - TheQrify</title>
                <meta name="description" content="Elevate your brochures and pamphlets with custom QR codes. Connect readers to videos, catalogs, and bookings instantly with TheQrify's free generator." />
                <script type="application/ld+json">
                    {JSON.stringify(faqSchema)}
                </script>
            </Helmet>

            {/* Hero Section */}
            <header className="hero-section">
                <Container>
                    <h1>QR Codes for <span>Brochures & Pamphlets</span></h1>
                    <p className="hero-subtitle">
                        Bridge the gap between your physical sales materials and your digital presence.
                        Perfect for real estate listings, product catalogs, and service guides.
                    </p>
                </Container>
            </header>

            <Container>
                {/* Generator Tool Section */}
                <section className="generator-card">
                    <Row className="g-4 align-items-center">
                        <Col lg={7}>
                            <h2 className="form-title">Brochure Details</h2>
                            <Form>
                                <Row>
                                    <Col md={6}>
                                        <div className="custom-form-group">
                                            <label htmlFor="brochureTitleInput">Brochure Title (Required)</label>
                                            <input
                                                id="brochureTitleInput"
                                                type="text"
                                                className="custom-input"
                                                placeholder="e.g. Service Guide 2026"
                                                value={brochureTitle}
                                                onChange={(e) => setBrochureTitle(e.target.value)}
                                                required
                                            />
                                        </div>
                                    </Col>
                                    <Col md={6}>
                                        <div className="custom-form-group">
                                            <label htmlFor="businessNameInput">Business Name (Required)</label>
                                            <input
                                                id="businessNameInput"
                                                type="text"
                                                className="custom-input"
                                                placeholder="e.g. Acme Services"
                                                value={businessName}
                                                onChange={(e) => setBusinessName(e.target.value)}
                                                required
                                            />
                                        </div>
                                    </Col>
                                </Row>

                                <Row>
                                    <Col md={6}>
                                        <div className="custom-form-group">
                                            <label htmlFor="ctaTextInput">Call to Action (Required)</label>
                                            <input
                                                id="ctaTextInput"
                                                type="text"
                                                className="custom-input"
                                                placeholder="e.g. Scan to View Catalog"
                                                value={ctaText}
                                                onChange={(e) => setCtaText(e.target.value)}
                                                required
                                            />
                                        </div>
                                    </Col>
                                    <Col md={6}>
                                        <div className="custom-form-group">
                                            <label htmlFor="brochureUrlInput">Digital Content URL (Required)</label>
                                            <input
                                                id="brochureUrlInput"
                                                type="url"
                                                className="custom-input"
                                                placeholder="https://yourbrand.com/digital-catalog"
                                                value={brochureUrl}
                                                onChange={(e) => setBrochureUrl(e.target.value)}
                                                required
                                            />
                                        </div>
                                    </Col>
                                </Row>
                                <small className="text-muted mt-2 d-block">
                                    Link to your online catalog, virtual tour, or booking page.
                                </small>
                                {!isAllFieldsFilled && (
                                    <div className="alert alert-info py-2 mt-3" style={{ borderRadius: '12px', fontSize: '0.9rem' }}>
                                        Please fill in all fields to generate the QR code.
                                    </div>
                                )}
                            </Form>
                        </Col>
                        <Col md={5}>
                            <div className="qr-preview-container">
                                <div className={`qr-wrapper ${!isAllFieldsFilled ? 'empty' : ''}`}>
                                    <QRCodeSVG
                                        id="brochure-qr-code"
                                        value={isAllFieldsFilled ? brochureUrl : 'https://theqrify.com'}
                                        size={220}
                                        includeMargin={true}
                                        level="H"
                                    />
                                </div>
                                <Button
                                    className="btn-download"
                                    onClick={downloadQRCode}
                                    disabled={!isAllFieldsFilled}
                                >
                                    <HiOutlineDownload className="me-2" /> Download Brochure QR
                                </Button>
                                <p className="text-muted small mt-3 mb-0 text-center">
                                    {isAllFieldsFilled ? 'High-resolution output for print ads' : 'Fill all fields to preview'}
                                </p>
                            </div>
                        </Col>
                    </Row>
                </section>

                {/* Features & Info Section */}
                <section className="info-section">
                    <h2>Modernize Your Sales Material</h2>
                    <Row className="g-4">
                        <Col md={4}>
                            <div className="benefit-card">
                                <div className="icon-wrapper"><FaBookOpen /></div>
                                <h3>Expanded Content</h3>
                                <p>Provide deep-dive information like detailed specs or brand stories without cluttering your brochure layout.</p>
                            </div>
                        </Col>
                        <Col md={4}>
                            <div className="benefit-card">
                                <div className="icon-wrapper"><FaInfoCircle /></div>
                                <h3>Real-time Updates</h3>
                                <p>Link to a landing page where you can update prices or availability without needing to reprint your brochures.</p>
                            </div>
                        </Col>
                        <Col md={4}>
                            <div className="benefit-card">
                                <div className="icon-wrapper"><FaHistory /></div>
                                <h3>Interactive Experience</h3>
                                <p>Engagement increases when you offer a digital path forward, like an 'Instant Quote' or 'Video Demo'.</p>
                            </div>
                        </Col>
                    </Row>

                    <Row className="mt-5 g-4">
                        <Col md={6}>
                            <h2>Implementation Guide</h2>
                            <ul className="list-unstyled mt-3">
                                <li className="mb-3 d-flex align-items-start">
                                    <FaArrowRight className="mt-1 me-2 text-primary" />
                                    <span>Define a clear goal (e.g., 'Scan to Book' or 'View Gallery').</span>
                                </li>
                                <li className="mb-3 d-flex align-items-start">
                                    <FaArrowRight className="mt-1 me-2 text-primary" />
                                    <span>Generate and download the high-res QR code.</span>
                                </li>
                                <li className="mb-3 d-flex align-items-start">
                                    <FaArrowRight className="mt-1 me-2 text-primary" />
                                    <span>Place on the back cover or inside panels of your brochure.</span>
                                </li>
                            </ul>
                        </Col>
                        <Col md={6}>
                            <div className="use-case-box">
                                <h3>Brochure Best Practices</h3>
                                <ul className="list-unstyled mb-0">
                                    <li className="mb-2"><FaCheckCircle className="me-2 text-success" /> **Context:** Explain what happens after scanning.</li>
                                    <li className="mb-2"><FaCheckCircle className="me-2 text-success" /> **Size:** Keep it readable on folded panels.</li>
                                    <li className="mb-2"><FaCheckCircle className="me-2 text-success" /> **Resolution:** High-res is a must for glossy paper.</li>
                                    <li className="mb-2"><FaCheckCircle className="me-2 text-success" /> **UTM:** Track scans from different brochures.</li>
                                </ul>
                            </div>
                        </Col>
                    </Row>
                </section>

                <section className="info-section faq-section">
                    <div className="faq-title">
                        <h1>FAQ – Brochure QR Codes</h1>
                        <p>Everything you need to know about digital-to-physical sales tools.</p>
                    </div>
                    <Row className="justify-content-center">
                        <Col lg={10}>
                            {[
                                {
                                    q: "How does a QR code benefit a brochure?",
                                    a: "It connects your physical brochure to digital content like videos, expanded pricing, or appointment booking, keeping the brochure design clean and focused."
                                },
                                {
                                    q: "Can I link to a PDF catalog?",
                                    a: "Yes! Just paste the direct URL of your hosted PDF catalog into the destination link, and customers can view it instantly."
                                },
                                {
                                    q: "Is there a limit on how many people can scan?",
                                    a: "No. The static QR codes generated by TheQrify have no scan limits and never expire."
                                }
                            ].map((item, index) => (
                                <FAQItem key={index} q={item.q} a={item.a} />
                            ))}
                        </Col>
                    </Row>
                </section>
            </Container>

            <LandingPageFooter currentPath='/qr-code-for-brochures' />
        </div>
    );
};

export default BrochuresQRCodeLandingPage;


