import React, { useState } from 'react';
import { Container, Row, Col, Form, Button, Collapse } from 'react-bootstrap';
import { QRCodeSVG } from 'qrcode.react';
import { Helmet } from 'react-helmet-async';
import {
    FaGlobe, FaRocket, FaMousePointer, FaChartLine,
    FaDownload, FaLaptopCode, FaShareAlt, FaCheck, FaExternalLinkAlt, FaLightbulb,
    FaArrowRight, FaCheckCircle
} from 'react-icons/fa';
import { HiOutlineDownload } from 'react-icons/hi';
import '../../css/WiFiQRCodeLandingPage.scss';
import LandingPageFooter from '../LandingPageFooter';

const FAQItem = ({ q, a }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (
        <div className="faq-item-custom mb-3">
            <button
                className={`faq-question-btn ${isOpen ? 'active' : ''}`}
                onClick={() => setIsOpen(!isOpen)}
                aria-expanded={isOpen}
            >
                <span>{q}</span>
                <span className="icon">{isOpen ? '−' : '+'}</span>
            </button>
            <Collapse in={isOpen}>
                <div className="faq-answer-content">
                    <p>{a}</p>
                </div>
            </Collapse>
        </div>
    );
};

const BusinessWebsiteQRCodeLandingPage = () => {
    const [businessName, setBusinessName] = useState('');
    const [websitePurpose, setWebsitePurpose] = useState('');
    const [websiteUrl, setWebsiteUrl] = useState('');

    const isAllFieldsFilled = businessName.trim() !== '' && websitePurpose.trim() !== '' && websiteUrl.trim() !== '';

    const downloadQRCode = () => {
        const svg = document.getElementById('website-qr-code');
        if (!svg) return;
        const svgData = new XMLSerializer().serializeToString(svg);
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        const img = new Image();
        img.onload = () => {
            canvas.width = img.width;
            canvas.height = img.height;
            ctx.drawImage(img, 0, 0);
            const pngFile = canvas.toDataURL('image/png');
            const downloadLink = document.createElement('a');
            downloadLink.download = `${businessName || 'business'}-website-qr.png`;
            downloadLink.href = pngFile;
            downloadLink.click();
        };
        img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
    };

    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": "Why should I use a QR code for my business website?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "A QR code removes the friction of typing a URL. It allows customers to visit your site instantly from business cards, store windows, or marketing materials."
                }
            },
            {
                "@type": "Question",
                "name": "Can I track how many people scan my website QR code?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes! We recommend using UTM parameters in your URL (e.g., mysite.com/?utm_source=qr) to track scans in Google Analytics."
                }
            },
            {
                "@type": "Question",
                "name": "Do these website QR codes ever expire?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "No. The static QR codes generated by TheQrify are permanent and will work as long as your website URL is active."
                }
            }
        ]
    };

    return (
        <div className="wifi-landing-container no-select">
            <Helmet>
                <title>QR Code for Business Website | Fast & Free URL QR - TheQrify</title>
                <meta name="description" content="Generate a professional QR code for your business website. Drive traffic, increase conversions, and simplify user access with TheQrify's free generator." />
                <script type="application/ld+json">
                    {JSON.stringify(faqSchema)}
                </script>
            </Helmet>

            {/* Hero Section */}
            <header className="hero-section">
                <Container>
                    <h1>QR Code for <span>Business Websites</span></h1>
                    <p className="hero-subtitle">
                        The easiest way to drive physical traffic to your digital storefront.
                        Create a high-quality QR code that links customers directly to your home page or landing page.
                    </p>
                </Container>
            </header>

            <Container>
                {/* Generator Tool Section */}
                <section className="generator-card">
                    <Row className="g-4 align-items-center">
                        <Col lg={7}>
                            <h2 className="form-title">Business Website Details</h2>
                            <Form>
                                <Row>
                                    <Col md={6}>
                                        <div className="custom-form-group">
                                            <label htmlFor="businessNameInput">Business Name (Required)</label>
                                            <input
                                                id="businessNameInput"
                                                type="text"
                                                className="custom-input"
                                                placeholder="e.g. Acme Innovations"
                                                value={businessName}
                                                onChange={(e) => setBusinessName(e.target.value)}
                                                required
                                            />
                                        </div>
                                    </Col>
                                    <Col md={6}>
                                        <div className="custom-form-group">
                                            <label htmlFor="websitePurposeInput">Website Purpose (Required)</label>
                                            <input
                                                id="websitePurposeInput"
                                                type="text"
                                                className="custom-input"
                                                placeholder="e.g. Product Portfolio"
                                                value={websitePurpose}
                                                onChange={(e) => setWebsitePurpose(e.target.value)}
                                                required
                                            />
                                        </div>
                                    </Col>
                                </Row>

                                <div className="custom-form-group">
                                    <label htmlFor="websiteUrlInput">Enter Your Website URL (Required)</label>
                                    <input
                                        id="websiteUrlInput"
                                        type="url"
                                        className="custom-input"
                                        placeholder="https://www.yourbusiness.com"
                                        value={websiteUrl}
                                        onChange={(e) => setWebsiteUrl(e.target.value)}
                                        required
                                    />
                                    <small className="text-muted mt-2 d-block">
                                        Tip: Use 'https://' for a secure and professional link.
                                    </small>
                                </div>
                                {!isAllFieldsFilled && (
                                    <div className="alert alert-info py-2" style={{ borderRadius: '12px', fontSize: '0.9rem' }}>
                                        Please fill in all fields to generate the QR code.
                                    </div>
                                )}
                            </Form>
                        </Col>
                        <Col md={5}>
                            <div className="qr-preview-container">
                                <div className={`qr-wrapper ${!isAllFieldsFilled ? 'empty' : ''}`}>
                                    <QRCodeSVG
                                        id="website-qr-code"
                                        value={isAllFieldsFilled ? websiteUrl : 'https://theqrify.com'}
                                        size={220}
                                        includeMargin={true}
                                        level="H"
                                    />
                                </div>
                                <Button
                                    className="btn-download"
                                    onClick={downloadQRCode}
                                    disabled={!isAllFieldsFilled}
                                >
                                    <HiOutlineDownload className="me-2" /> Download Website QR
                                </Button>
                                <p className="text-muted small mt-3 mb-0 text-center">
                                    {isAllFieldsFilled ? 'Optimized for all digital & print media' : 'Fill all fields to preview'}
                                </p>
                            </div>
                        </Col>
                    </Row>
                </section>

                {/* Features & Info Section */}
                <section className="info-section">
                    <h2>Boost Your Online Presence</h2>
                    <Row className="g-4">
                        <Col md={4}>
                            <div className="benefit-card">
                                <div className="icon-wrapper"><FaRocket /></div>
                                <h3>Instant Access</h3>
                                <p>Customers can jump to your site in seconds. Perfect for restaurant menus, shop fronts, and service catalogs.</p>
                            </div>
                        </Col>
                        <Col md={4}>
                            <div className="benefit-card">
                                <div className="icon-wrapper"><FaChartLine /></div>
                                <h3>Conversion Ready</h3>
                                <p>Link directly to a 'Buy Now' page or 'Book Appointment' form to capture customers while their interest is peaked.</p>
                            </div>
                        </Col>
                        <Col md={4}>
                            <div className="benefit-card">
                                <div className="icon-wrapper"><FaMousePointer /></div>
                                <h3>Zero Friction</h3>
                                <p>Avoid the risk of typos in your web address. One scan leads exactly where you want your customers to go.</p>
                            </div>
                        </Col>
                    </Row>

                    <Row className="mt-5 g-4">
                        <Col md={6}>
                            <h2>Strategic Placements</h2>
                            <ul className="list-unstyled mt-3">
                                <li className="mb-3 d-flex align-items-start">
                                    <FaArrowRight className="mt-1 me-2 text-primary" />
                                    <span>**Storefronts:** Let passersby browse your shop even after hours.</span>
                                </li>
                                <li className="mb-3 d-flex align-items-start">
                                    <FaArrowRight className="mt-1 me-2 text-primary" />
                                    <span>**Business Cards:** A digital bridge from a physical introduction.</span>
                                </li>
                                <li className="mb-3 d-flex align-items-start">
                                    <FaArrowRight className="mt-1 me-2 text-primary" />
                                    <span>**Packaging:** Link to 'How-to' guides or supplementary products.</span>
                                </li>
                            </ul>
                        </Col>
                        <Col md={6}>
                            <div className="use-case-box">
                                <h3>Professional Tips</h3>
                                <ul className="list-unstyled mb-0">
                                    <li className="mb-2"><FaCheckCircle className="me-2 text-success" /> **Mobile Friendly:** Ensure your site looks great on phones!</li>
                                    <li className="mb-2"><FaCheckCircle className="me-2 text-success" /> **Short URLs:** Use clean, shorter links for better scannability.</li>
                                    <li className="mb-2"><FaCheckCircle className="me-2 text-success" /> **UTM Tracking:** Always track which QR placement works best.</li>
                                    <li className="mb-2"><FaCheckCircle className="me-2 text-success" /> **Testing:** Test the scan on both Android and iOS devices.</li>
                                </ul>
                            </div>
                        </Col>
                    </Row>
                </section>

                <section className="info-section faq-section">
                    <div className="faq-title">
                        <h1>FAQ – Website QR Codes</h1>
                        <p>Everything you need to know about linking your business to the web.</p>
                    </div>
                    <Row className="justify-content-center">
                        <Col lg={10}>
                            {[
                                {
                                    q: "Why should I use a QR code for my business website?",
                                    a: "A QR code removes the friction of typing a URL. It allows customers to visit your site instantly from business cards, store windows, or marketing materials."
                                },
                                {
                                    q: "Can I track how many people scan my website QR code?",
                                    a: "Yes! We recommend using UTM parameters in your URL (e.g., mysite.com/?utm_source=qr) to track scans in Google Analytics."
                                },
                                {
                                    q: "Do these website QR codes ever expire?",
                                    a: "No. The static QR codes generated by TheQrify are permanent and will work as long as your website URL is active."
                                }
                            ].map((item, index) => (
                                <FAQItem key={index} q={item.q} a={item.a} />
                            ))}
                        </Col>
                    </Row>
                </section>
            </Container>


            <LandingPageFooter currentPath='/qr-code-for-business-website' />
        </div>
    );
};

export default BusinessWebsiteQRCodeLandingPage;


