import React, { useState } from 'react';
import { Container, Row, Col, Form, Button, Collapse } from 'react-bootstrap';
import { QRCodeSVG } from 'qrcode.react';
import { Helmet } from 'react-helmet-async';
import {
    FaDownload, FaCloudUploadAlt, FaEdit,
    FaMobileAlt, FaLink, FaChartBar, FaTable, FaCalculator
} from 'react-icons/fa';
import '../../css/GoogleSheetsQRCodeLandingPage.scss';
import LandingPageFooter from '../LandingPageFooter';

const FAQItem = ({ q, a }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (
        <div className="faq-item-custom mb-3">
            <button
                className={`faq-question-btn ${isOpen ? 'active' : ''}`}
                onClick={() => setIsOpen(!isOpen)}
                aria-expanded={isOpen}
            >
                <span>{q}</span>
                <span className="icon">{isOpen ? '−' : '+'}</span>
            </button>
            <Collapse in={isOpen}>
                <div className="faq-answer-content">
                    <p>{a}</p>
                </div>
            </Collapse>
        </div>
    );
};

const GoogleSheetsQRCodeLandingPage = () => {
    const [sheetUrl, setSheetUrl] = useState('');
    const [fileName, setFileName] = useState('');

    
    const isAllFieldsFilled = sheetUrl.trim() !== '' && fileName.trim() !== '';

const downloadQRCode = () => {
        const svg = document.getElementById('google-sheets-qr-code');
        if (!svg) return;
        const svgData = new XMLSerializer().serializeToString(svg);
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        const img = new Image();
        img.onload = () => {
            canvas.width = img.width;
            canvas.height = img.height;
            ctx.drawImage(img, 0, 0);
            const pngFile = canvas.toDataURL('image/png');
            const downloadLink = document.createElement('a');
            downloadLink.download = `${fileName || 'google-sheet'}-qr.png`;
            downloadLink.href = pngFile;
            downloadLink.click();
        };
        img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
    };

    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": "How do I create a QR code for a Google Sheet?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Open your Google Sheet, click the 'Share' button, set access to 'Anyone with the link', copy that URL and paste it into our generator above."
                }
            },
            {
                "@type": "Question",
                "name": "Can I link to a specific tab in the sheet?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes! Navigate to the specific tab in your browser, copy the full URL from the address bar (which includes the gid parameter), and use that for your QR code."
                }
            },
            {
                "@type": "Question",
                "name": "Are the QR codes permanent?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes, the QR codes generated by TheQrify are static and do not expire. They will work as long as your Google Sheet link remains active."
                }
            }
        ]
    };

    return (
        <div className="gsheets-landing-container no-select">
            <Helmet>
                <title>Free Google Sheets QR Code Generator | Share Spreadsheets | TheQrify</title>
                <meta name="description" content="Generate QR codes for your Google Sheets for free. Share data, charts, and inventories instantly with scannable paths to your cloud spreadsheets." />
                <script type="application/ld+json">
                    {JSON.stringify(faqSchema)}
                </script>
            </Helmet>

            {/* Hero Section */}
            <header className="hero-section">
                <Container>
                    <h1>Convert <span>Google Sheets to QR Code</span></h1>
                    <p className="hero-subtitle">
                        Share live data, reports, and inventories effortlessly.
                        Create a professional QR code that links directly to your shared Google Sheet or spreadsheet calculator.
                    </p>
                </Container>
            </header>

            <Container>
                {/* Generator Card */}
                <section className="generator-card">
                    <Row className="align-items-center">
                        <Col lg={7}>
                            <div className="form-title">
                                <FaTable className="me-2" />
                                <span>Spreadsheet Linking</span>
                            </div>
                            <Form>
                                <div className="custom-form-group">
                                    <label htmlFor="fileNameInput">Sheet Name (Required)</label>
                                    <input
                                        id="fileNameInput"
                                        type="text"
                                        className="custom-input"
                                        placeholder="E.g. Inventory Tracker 2026"
                                        value={fileName}
                                        onChange={(e) => setFileName(e.target.value)}
                                        required
                                    />
                                </div>
                                <div className="custom-form-group">
                                    <label htmlFor="sheetUrlInput">Google Sheets Share URL (Required)</label>
                                    <input
                                        id="sheetUrlInput"
                                        type="url"
                                        className="custom-input"
                                        placeholder="https://docs.google.com/spreadsheets/d/..."
                                        value={sheetUrl}
                                        onChange={(e) => setSheetUrl(e.target.value)}
                                        required
                                    />
                                    <small className="text-muted mt-2 d-block">
                                        Pro Tip: Use the 'Publish to the web' link for faster loading on mobile browsers.
                                    </small>
                                </div>
                                                            {!isAllFieldsFilled && (
                                    <div className="alert alert-info py-2" style={{ borderRadius: '12px', fontSize: '0.9rem' }}>
                                        Please fill in all fields to generate the QR code.
                                    </div>
                                )}

                            </Form>
                        </Col>
                        <Col lg={5} className="mt-4 mt-lg-0">
                            <div className="qr-preview-container">
                                <div className={`qr-wrapper ${!isAllFieldsFilled ? 'empty' : ''}`}>
                                    <QRCodeSVG
                                        id="google-sheets-qr-code"
                                        value={isAllFieldsFilled ? sheetUrl : 'https://theqrify.com'}
                                        size={220}
                                        includeMargin={true}
                                        level="H"
                                    />
                                </div>
                                <Button
                                    className="btn-download"
                                    onClick={downloadQRCode}
                                    disabled={!isAllFieldsFilled}
                                >
                                    <FaDownload className="me-2" /> Download Sheet QR
                                </Button>
                                <p className="text-muted small mt-3 mb-0 text-center">
                                    {isAllFieldsFilled ? 'Ready to share on flyers and business cards' : 'Fill all fields to preview'}
                                </p>
                            </div>
                        </Col>
                    </Row>
                </section>

                {/* Benefits Section */}
                <section className="info-section">
                    <h2>Live Data at Your Fingertips</h2>
                    <Row className="g-4">
                        <Col md={4}>
                            <div className="benefit-card">
                                <div className="icon-wrapper"><FaChartBar /></div>
                                <h3>Visual Reporting</h3>
                                <p>Link directly to real-time dashboards and charts. Perfect for sharing project progress during presentations.</p>
                            </div>
                        </Col>
                        <Col md={4}>
                            <div className="benefit-card">
                                <div className="icon-wrapper"><FaEdit /></div>
                                <h3>Dynamic Content</h3>
                                <p>Update your spreadsheet data anytime. Your QR code remains the same while always showing the latest information.</p>
                            </div>
                        </Col>
                        <Col md={4}>
                            <div className="benefit-card">
                                <div className="icon-wrapper"><FaCalculator /></div>
                                <h3>Interactive Tools</h3>
                                <p>Share custom calculators or feedback forms. Let users interact with your spreadsheets instantly on mobile.</p>
                            </div>
                        </Col>
                    </Row>
                </section>

                {/* Guide Section */}
                <section className="info-section">
                    <Row className="g-5 align-items-center">
                        <Col lg={6}>
                            <div className="gsheets-guide-box">
                                <h3>Business Use Cases</h3>
                                <div className="guide-item">
                                    <div className="guide-bullet"></div>
                                    <p><strong>Stock Control:</strong> Place QR codes on shelves to let staff update inventory counts in a shared sheet.</p>
                                </div>
                                <div className="guide-item">
                                    <div className="guide-bullet"></div>
                                    <p><strong>Lead Tracking:</strong> Share sheets with sales teams on the field to log data into a central master file.</p>
                                </div>
                                <div className="guide-item">
                                    <div className="guide-bullet"></div>
                                    <p><strong>Price Lists:</strong> Provide customers with a scannable link to your most current pricing spreadsheets.</p>
                                </div>
                                <div className="guide-item">
                                    <div className="guide-bullet"></div>
                                    <p><strong>Event Attendance:</strong> Link to a sign-in sheet for guests to register their arrival via their own phones.</p>
                                </div>
                            </div>
                        </Col>
                        <Col lg={6}>
                            <h3>How to link your Sheet?</h3>
                            <p className="text-muted mb-4">
                                Google Sheets gives you multiple ways to share your data:
                            </p>
                            <ul className="list-unstyled">
                                <li className="mb-3 d-flex align-items-center">
                                    <FaLink className="me-3" /> <strong>Shared Link:</strong> Click 'Share' → 'Anyone with the link' → 'Viewer/Editor'.
                                </li>
                                <li className="mb-3 d-flex align-items-center">
                                    <FaLink className="me-3" /> <strong>Web Publication:</strong> File → Share → Publish to the web (best for public dashboards).
                                </li>
                                <li className="mb-3 d-flex align-items-center">
                                    <FaLink className="me-3" /> <strong>Forms Link:</strong> Link directly to the attached Google Form for data entry.
                                </li>
                            </ul>
                        </Col>
                    </Row>
                </section>

                {/* FAQ Section */}
                <section className="info-section faq-section">
                    <h2>Got Questions?</h2>
                    <Row className="justify-content-center">
                        <Col lg={10}>
                            {[
                                {
                                    q: "Can I use this for Microsoft Excel files?",
                                    a: "Yes! If your Excel file is hosted on OneDrive or SharePoint, just paste the shareable link here. You can also import Excel files into Google Sheets and use that link."
                                },
                                {
                                    q: "Will the QR code work if the link is private?",
                                    a: "The QR code will scan, but users will be prompted to log in to their Google account to request access. For public ease of use, we recommend 'Anyone with the link' settings."
                                },
                                {
                                    q: "Is there a limit to how much data I can share?",
                                    a: "The QR code only stores the link, so the limit depends entirely on your Google Sheets storage and cell limits."
                                }
                            ].map((item, index) => (
                                <FAQItem key={index} q={item.q} a={item.a} />
                            ))}
                        </Col>
                    </Row>
                </section>
            </Container>

            <LandingPageFooter currentPath='/qr-code-for-google-sheets' />
        </div>
    );
};

export default GoogleSheetsQRCodeLandingPage;
